---
name: Crypt-OpenSSL-CA
version: 0.04
author:
  - 'Dominique Quatravaux <domq@cpan.org>'
abstract: The crypto parts of an X509v3 Certification Authority
license: perl
requires:
  Convert::ASN1: 0.2
build_requires:
  Devel::Leak: 0
  Fatal: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  File::Temp: 0
  FindBin: 0
  IO::Pipe: 0
  IPC::Run: 0
  Inline: 0.4
  Memchmark: 0
  Net::SSLeay: 1.25
  Sub::Uplevel: 0.09
  Test::Group: 0
  Test::More: 0
provides:
  Crypt::OpenSSL::CA:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::CONF:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::ENGINE:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::Error:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::Inline::C:
    file: lib/Crypt/OpenSSL/CA/Inline/C.pm
  Crypt::OpenSSL::CA::PrivateKey:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::PublicKey:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::X509:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::X509V3_EXT:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::X509_CRL:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
  Crypt::OpenSSL::CA::X509_NAME:
    file: lib/Crypt/OpenSSL/CA.pm
    version: 0.04
generated_by: Module::Build version 0.26
no_index:
  directory:
    - example
    - inc
    - t
